---
stages:
- name: RapidAssemble
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: WrapPresent
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      ##########
      # Colors##
      ##########
      Green='\x1B[0;32m'
      Red='\x1B[0;31m'
      Yellow='\x1B[0;33m'
      Cyan='\x1B[0;36m'
      no_color='\x1B[0m' # No Color
      beer='\xF0\x9f\x8d\xba'
      delivery='\xF0\x9F\x9A\x9A'
      beers='\xF0\x9F\x8D\xBB'
      eyes='\xF0\x9F\x91\x80'
      cloud='\xE2\x98\x81'
      crossbones='\xE2\x98\xA0'
      litter='\xF0\x9F\x9A\xAE'
      fail='\xE2\x9B\x94'
      harpoons='\xE2\x87\x8C'
      tools='\xE2\x9A\x92'
      present='\xF0\x9F\x8E\x81'
      hourglass='\xE2\x8F\xB3'
      #############
      git config --global user.email "pipeline@example.com"
      git config --global user.name "Pipeline Builder"

- name: SameDayDelivery
  inputs:
  - type: job
    stage: RapidAssemble
    job: WrapPresent
  triggers:
  - type: stage
  jobs:
  - name: Services
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      ##########
      # Colors##
      ##########
      Green='\x1B[0;32m'
      Red='\x1B[0;31m'
      Yellow='\x1B[0;33m'
      Cyan='\x1B[0;36m'
      no_color='\x1B[0m' # No Color
      beer='\xF0\x9f\x8d\xba'
      delivery='\xF0\x9F\x9A\x9A'
      beers='\xF0\x9F\x8D\xBB'
      eyes='\xF0\x9F\x91\x80'
      cloud='\xE2\x98\x81'
      crossbones='\xE2\x98\xA0'
      litter='\xF0\x9F\x9A\xAE'
      fail='\xE2\x9B\x94'
      harpoons='\xE2\x87\x8C'
      tools='\xE2\x9A\x92'
      present='\xF0\x9F\x8E\x81'
      hourglass='\xE2\x8F\xB3'
      #############
      if [ -n "$(echo ${CF_TARGET_URL} | grep ng.bluemix.net)" ]; then
        echo -e "${tools}${Cyan}  Detected Region: US South${no_color}"
        export CF_REGION=US
      elif [ -n "$(echo ${CF_TARGET_URL} | grep eu-gb.bluemix.net)" ]; then
        echo -e "${tools}${Cyan}  Detected Region: United Kingdom${no_color}"
        export CF_REGION=UK
      elif [ -n "$(echo ${CF_TARGET_URL} | grep au-syd.bluemix.net)" ]; then
        echo -e "${tools}${Cyan}  Detected Region: Sydney${no_color}"
        export CF_REGION=AU
      fi
      # Create CF services
      echo -e "${tools}${Cyan}  Creating Compose MySQL Service Instance${no_color}"
      t=0
      until [ $t -ge 5 ]
      do
        cf create-service compose-for-mysql Standard myComposeMySQL > /dev/null 2>&1 && break
        t=$[$t+1]
        sleep 15
      done

      if [ ${CF_REGION} == "AU" ]; then
        echo -e "${crossbones}${Yellow}    Object Storage service not available in this region${no_color}"
      else
        echo -e "${tools}${Cyan}  Creating Openstack Swift Object Storage Service Instance${no_color}"
        t=0
        until [ $t -ge 5 ]
        do
          cf create-service Object-Storage standard myObjectStorage > /dev/null 2>&1 && break
          t=$[$t+1]
          sleep 15
        done
        while :
        do
          status=$(cf s | grep myObjectStorage | awk -F" " '{print $5, $6}')
          if [[ "$status" == *"succeeded"* ]]
          then
            break
          fi
        done
      fi
      sleep 3m
  - name: DeliverPresent
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"

      # View logs
      #cf logs "${CF_APP}" --recent

